#!/bin/bash

if [ "$#" == "0" ]; then 
  echo "Usage: whoavail domain1.com domain2.net
       whoavail filename.lst
       whoavail abcdfg.{com,net,org}
       whoavail domain{1,2,3}.com
       whoavail {abcd,efgh,jklm}.{com,net,org}
       whoavail {a..z}domain.{com,net,org} | tee -a domainavail.lst
       whoavail {a..z}{a..z}{a..z}.{com,net,org} | tee -a domainavail.lst
       
If you give the first parameter the filename of a text file (filename.lst) containing a list of domainnames (one domain in a line) all the lines in this file will be processed as a domain name."
  exit 1
fi 

#coloured text
#green='\033[0;32m'
#red='\033[0;31m'
#reset='\033[0m'

#plain text
green=''
red=''
reset=''

# if the first param is a file read the domainlist from that file otherwise process all the params
if test -f "$1"; then
  domainlist=$(cat $1)
else
  domainlist="$@"
fi

for domainname in $domainlist
do

  time=$(date +%y%m%d-%H%M%S)
  filename=$time"_"${domainname}".whois_out"
  
  whoisresult=$(whois ${domainname} > ${filename})
    
  results=$(egrep -q '^No match|^NOT FOUND|^Not fo|AVAILABLE|^No Data Fou|has not been regi|No entri|DOMAIN NOT FOUND' $filename)
  returncode=$?
  
  if [ $returncode -eq 0 ]; then
    echo -e "${time}\t${green}Available${reset}\t${domainname}"
  else
    echo -e "${time}\t${red}NOT Available${reset}\t${domainname}"
  fi

  sleep 0.1
 
done
